blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/programmingpioneer/live-api-inspector/discussions
    about: Ask questions and discuss ideas  # Replace programmingpioneer before publishing